Repository klab-mtot/mtot-backend, pull requests merged in 2023-06, with the labels that each got.

#19 feat: 위치, 사진, 핀 구현
  build.gradle
  src/main/java/org/konkuk/klab/mtot/config/S3Config.java
  src/main/java/org/konkuk/klab/mtot/domain/Journey.java
  src/main/java/org/konkuk/klab/mtot/domain/Location.java
  src/main/java/org/konkuk/klab/mtot/domain/Photo.java
  src/main/java/org/konkuk/klab/mtot/domain/Pin.java
  src/main/java/org/konkuk/klab/mtot/domain/Post.java
  src/main/java/org/konkuk/klab/mtot/dto/response/CreateJourneyResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/CreatePinResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/PhotoUploadResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/PinUpdateResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/PostEditResponse.java
  src/main/java/org/konkuk/klab/mtot/exception/PinNotFound.java
  src/main/java/org/konkuk/klab/mtot/exception/PostNotFoundException.java
  src/main/java/org/konkuk/klab/mtot/repository/PhotoRepository.java
  src/main/java/org/konkuk/klab/mtot/repository/PinRepository.java
  src/main/java/org/konkuk/klab/mtot/s3/AwsS3FileSupporter.java
  src/main/java/org/konkuk/klab/mtot/service/JourneyService.java
  src/main/java/org/konkuk/klab/mtot/service/PhotoService.java
  src/main/java/org/konkuk/klab/mtot/service/PinService.java
  src/main/java/org/konkuk/klab/mtot/service/PostService.java
  src/main/resources/application.yaml
  src/test/java/org/konkuk/klab/mtot/service/PhotoServiceTest.java
  src/test/java/org/konkuk/klab/mtot/service/PinServiceTest.java
  src/test/java/org/konkuk/klab/mtot/service/PostServiceTest.java
Labels: 기능구현 🛫

#18 feat: Journey + Post + Photo
  build.gradle
  src/main/java/org/konkuk/klab/mtot/config/S3Config.java
  src/main/java/org/konkuk/klab/mtot/domain/Journey.java
  src/main/java/org/konkuk/klab/mtot/domain/Location.java
  src/main/java/org/konkuk/klab/mtot/domain/Photo.java
  src/main/java/org/konkuk/klab/mtot/domain/Pin.java
  src/main/java/org/konkuk/klab/mtot/domain/Post.java
  src/main/java/org/konkuk/klab/mtot/domain/Team.java
  src/main/java/org/konkuk/klab/mtot/dto/request/MemberSignUpRequest.java
  src/main/java/org/konkuk/klab/mtot/dto/response/CreateJourneyResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/CreatePinResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/PhotoUploadResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/PinUpdateResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/PostCreateResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/PostEditResponse.java
  src/main/java/org/konkuk/klab/mtot/exception/DuplicatePostException.java
  src/main/java/org/konkuk/klab/mtot/exception/JourneyNotFoundException.java
  src/main/java/org/konkuk/klab/mtot/exception/PinNotFound.java
  src/main/java/org/konkuk/klab/mtot/exception/PostNotFoundException.java
  src/main/java/org/konkuk/klab/mtot/exception/TeamAccessDeniedException.java
  src/main/java/org/konkuk/klab/mtot/repository/JourneyRepository.java
  src/main/java/org/konkuk/klab/mtot/repository/PhotoRepository.java
  src/main/java/org/konkuk/klab/mtot/repository/PinRepository.java
  src/main/java/org/konkuk/klab/mtot/repository/PostRepository.java
  src/main/java/org/konkuk/klab/mtot/s3/AwsS3FileSupporter.java
  src/main/java/org/konkuk/klab/mtot/service/JourneyService.java
  src/main/java/org/konkuk/klab/mtot/service/PhotoService.java
  src/main/java/org/konkuk/klab/mtot/service/PinService.java
  src/main/java/org/konkuk/klab/mtot/service/PostService.java
  src/main/resources/application.yaml
  src/test/java/org/konkuk/klab/mtot/service/JourneyServiceTest.java
  src/test/java/org/konkuk/klab/mtot/service/MemberServiceTest.java
  src/test/java/org/konkuk/klab/mtot/service/PhotoServiceTest.java
  src/test/java/org/konkuk/klab/mtot/service/PinServiceTest.java
  src/test/java/org/konkuk/klab/mtot/service/PostServiceTest.java
Labels: 기능구현 🛫

#16 refactor: Google OAuth2 추가 구현사항
  src/main/java/org/konkuk/klab/mtot/exception/InvalidTokenException.java
  src/main/java/org/konkuk/klab/mtot/exception/TokenExpiredException.java
  src/main/java/org/konkuk/klab/mtot/oauth/GoogleOAuthLoginSupporter.java
  src/main/java/org/konkuk/klab/mtot/oauth/JwtService.java
  src/test/java/org/konkuk/klab/mtot/oauth/JwtServiceTest.java
Labels: 리팩터링 🛠

#10 친구 관련 기능 구현
  src/main/java/org/konkuk/klab/mtot/domain/Friendship.java
  src/main/java/org/konkuk/klab/mtot/dto/request/FriendCheckRequest.java
  src/main/java/org/konkuk/klab/mtot/dto/request/FriendshipCheckRequest.java
  src/main/java/org/konkuk/klab/mtot/dto/request/FriendshipRequest.java
  src/main/java/org/konkuk/klab/mtot/dto/request/FriendshipUpdateRequest.java
  src/main/java/org/konkuk/klab/mtot/dto/response/FriendCheckResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/FriendshipAcceptCheckResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/FriendshipCheckResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/FriendshipResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/FriendshipUpdateResponse.java
  src/main/java/org/konkuk/klab/mtot/exception/AlreadyFriendException.java
  src/main/java/org/konkuk/klab/mtot/exception/DuplicateFriendshipException.java
  src/main/java/org/konkuk/klab/mtot/exception/FriendshipNotFoundException.java
  src/main/java/org/konkuk/klab/mtot/repository/FriendshipRepository.java
  src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
  src/test/java/org/konkuk/klab/mtot/service/FriendServiceTest.java
Labels: 기능구현 🛫

#24 feat: PostController 추가
  src/main/java/org/konkuk/klab/mtot/controller/PostController.java
  src/main/java/org/konkuk/klab/mtot/dto/request/CreatePostRequest.java
  src/main/java/org/konkuk/klab/mtot/dto/request/EditPostRequest.java
  src/main/java/org/konkuk/klab/mtot/dto/response/CreatePostResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/EditPostResponse.java
  src/main/java/org/konkuk/klab/mtot/service/PostService.java
Labels: 기능구현 🛫, API 수정 👀

#21 fix: S3 수정
  src/main/java/org/konkuk/klab/mtot/domain/Photo.java
  src/main/java/org/konkuk/klab/mtot/s3/AwsS3FileSupporter.java
  src/main/java/org/konkuk/klab/mtot/service/PhotoService.java
Labels: 리팩터링 🛠

#27 fix: Postmapping 중복 해결
  src/main/java/org/konkuk/klab/mtot/controller/PostController.java
Labels: 심각한 버그 🐛

#28 Fix: Friendship 수정
  src/main/java/org/konkuk/klab/mtot/controller/FriendshipController.java
  src/main/java/org/konkuk/klab/mtot/dto/request/CreatePostRequest.java
  src/main/java/org/konkuk/klab/mtot/dto/request/EditPostRequest.java
  src/main/java/org/konkuk/klab/mtot/dto/request/FriendCheckRequest.java
  src/main/java/org/konkuk/klab/mtot/dto/request/FriendshipAcceptRequest.java
  src/main/java/org/konkuk/klab/mtot/dto/request/FriendshipRequest.java
Labels: 심각한 버그 🐛

#33 fix: 그룹에 멤버가 추가되지 않던 버그 수정
  src/main/java/org/konkuk/klab/mtot/service/MemberTeamService.java
Labels: 심각한 버그 🐛

#36 fix: Post recursive 오류 수정
  src/main/java/org/konkuk/klab/mtot/dto/response/GetJourneyResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/PostInfoResponse.java
  src/main/java/org/konkuk/klab/mtot/service/JourneyService.java
Labels: 심각한 버그 🐛

#43 feat: API 필드 수정
  src/main/java/org/konkuk/klab/mtot/dto/response/CreatePostResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/EditPostResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/GetAllFriendshipInfoResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/MemberTeamGetAllResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/MemberTeamJoinResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/PhotoUploadResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/PinFromJourneyResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/PinUpdateResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/SendFriendshipResponse.java
  src/main/java/org/konkuk/klab/mtot/dto/response/TeamCreateResponse.java
  src/test/java/org/konkuk/klab/mtot/service/FriendServiceTest.java
  src/test/java/org/konkuk/klab/mtot/service/MemberTeamServiceTest.java
  src/test/java/org/konkuk/klab/mtot/service/PinServiceTest.java
Labels: API 수정 👀, 리팩터링 🛠

#44 refactor: API Endpoint 수정: Request로 email 받기
  src/main/java/org/konkuk/klab/mtot/controller/MemberTeamController.java
  src/main/java/org/konkuk/klab/mtot/dto/request/MemberTeamJoinRequest.java
  src/main/java/org/konkuk/klab/mtot/repository/MemberTeamRepository.java
  src/main/java/org/konkuk/klab/mtot/service/MemberTeamService.java
  src/main/java/org/konkuk/klab/mtot/service/TeamService.java
  src/test/java/org/konkuk/klab/mtot/service/MemberTeamServiceTest.java
Labels: API 수정 👀

#45 friendship 중복 검사 오류
  src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
Labels: 심각한 버그 🐛

#47 /teams 요청 시 다른 id 반환 에러 수정
  src/main/java/org/konkuk/klab/mtot/service/MemberTeamService.java
Labels: 심각한 버그 🐛

#49 Infra: Github Actions를 이용한 CI 스크립트 작성
  .github/workflows/gradle.yml
  src/test/resources/application.yaml
Labels: 인프라 🌎
